
# Site settings

url: "https://thatsk.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: /thatsk.github.io

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

#############
# HTML Head #
#############

lang: "en"
author: "Thatsk"
title: "System Administrator"
description: "Blog and website of Thatsk, blogging mainly for tech. Feel Free to Share"
keywords: "thatsk, kunalsing, thakur, theme"
favicon: "/img/favicon.ico"
##########
# Header #
##########

black-favicon: "/img/black-lab-glass.ico"
me-img: "/img/jetpacktocat.png"

background-type: "3d-lines" # It can be either image, 3d-lines or color-gradient.

# Options for image configuration

background-img: "../img/certificate.jpg"

# The following configurations are common for both color-gradient and 3d-lines options

background-color-shuffle: True	# Keep shuffle True to get different background every time.
background-colors: # You must add at least 4 colors.
  - color: "4dd0e1" # Color Hex Codes.
  - color: "00bcd4"
  - color: "0097a7"
  - color: "006064"

background-color-trasition-speed: 0.001
background-color-update-interval: 1

# 3d-lines configuration

background-lines-color: "b2ebf2"
background-particles: 100

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 4
start-delay: 2000
delete-delay: 50000
lines: # You can add HTML tags in the Text
  - text: "rm -rf /"
  - text: "Just Think about it???"
me-img: "/img/profile.jpg"
########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
pinterest-share: True
vkontakte-share: True
disqus-shortname: "panossakkos"

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "August 2016 - Today"
    description: "Fun With technology"
  - image: "/img/timeline/baracktocat.jpg"
    date: "August 2015 - August 2016"
    description: "Started Learning"

# First image of the Career timeline

career-img: "/img/career/default.png"

###########
# Contact #
###########

email: "kunalsingthakur@gmail.com"


##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/kunalsing452"
  - title: "twitter"
    url: "https://twitter.com/kunalsingthakur"
  - title: "github"
    url: "https://github.com/thatsk"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/kunalsing-thakur-0a73887b"
  - title: "rss"
    url: "/feed.xml"
############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems: [jekyll-paginate]
